config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :spaces
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/feature.rb
# == Schema Information
#
# Table name: features
#
#  id         :bigint           not null, primary key
#  name       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_features_on_name  (name) UNIQUE
#
class Feature < ApplicationRecord
   validates :name, presence: true
end

app/models/feature_mapping.rb
# == Schema Information
#
# Table name: feature_mappings
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  feature_id :bigint           not null
#  space_id   :bigint           not null
#
# Indexes
#
#  index_feature_mappings_on_feature_id               (feature_id)
#  index_feature_mappings_on_feature_id_and_space_id  (feature_id,space_id) UNIQUE
#  index_feature_mappings_on_space_id                 (space_id)
#
# Foreign Keys
#
#  fk_rails_...  (feature_id => features.id)
#  fk_rails_...  (space_id => spaces.id)
#
class FeatureMapping < ApplicationRecord
  belongs_to :space
  belongs_to :feature
end

app/models/space.rb
# == Schema Information
#
# Table name: spaces
#
#  id              :bigint           not null, primary key
#  address         :string(255)
#  description     :text(65535)      not null
#  latitude        :float(24)
#  longitude       :float(24)
#  name            :string(255)      not null
#  nearest_station :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class Space < ApplicationRecord

  has_many_attached :images

  has_many :space_type_mappings, dependent: :destroy
  has_many :space_types, through: :space_type_mappings
  has_many :feature_mappings, dependent: :destroy
  has_many :features, through: :feature_mappings

  validates :name, presence: true
  validates :description, presence: true

  def main_image
    images.first || 'http://placehold.jp/300x200.png'
  end
end

app/models/space_type.rb
# == Schema Information
#
# Table name: space_types
#
#  id         :bigint           not null, primary key
#  name       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_space_types_on_name  (name) UNIQUE
#
class SpaceType < ApplicationRecord
   validates :name, presence: true
end

app/models/space_type_mapping.rb
# == Schema Information
#
# Table name: space_type_mappings
#
#  id            :bigint           not null, primary key
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  space_id      :bigint           not null
#  space_type_id :bigint           not null
#
# Indexes
#
#  index_space_type_mappings_on_space_id                    (space_id)
#  index_space_type_mappings_on_space_type_id               (space_type_id)
#  index_space_type_mappings_on_space_type_id_and_space_id  (space_type_id,space_id) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (space_id => spaces.id)
#  fk_rails_...  (space_type_id => space_types.id)
#
class SpaceTypeMapping < ApplicationRecord
  belongs_to :space
  belongs_to :space_type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  add_flash_types :info, :success, :warning, :error
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @q = Space.ransack(params[:q])
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  def index
    @q = Space.ransack(params[:q])
    @pagy, @spaces = pagy(@q.result.includes(:features).order(created_at: :desc))
  end

  def new
    @space = Space.new
  end

  def create
    @space = Space.new(space_params)
    if @space.save
      redirect_to @space, success: '作成しました'
    else
      flash.now[:error] = '失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @space = Space.find(params[:id])
  end

  def update
    @space = Space.find(params[:id])
    if @space.update(space_params)
      redirect_to @space, success: '更新しました'
    else
      flash.now[:error] = '失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @space = Space.find(params[:id])
  end

  private

  def space_params
    params.require(:space).permit(:name, :description, :address, :nearest_station, { space_type_ids: [] },
                                  { feature_ids: [] }, :longitude, :latitude, { images: [] })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/home/index.html.erb
<div class="hero min-h-screen" style="background-image: url(<%= asset_url('hero.jpg') %>);">
  <div class="hero-overlay bg-opacity-60"></div>
  <div class="hero-content text-center max-w-none w-full">
    <div class="w-full">
      <%= render 'shared/search_form' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentalSpacePractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script async
      src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.google_map_api_key %>">
    </script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/flash/flash' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer p-10 bg-neutral text-neutral-content">
  <div>
    <svg width="50" height="50" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" class="fill-current"><path d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z"></path></svg>
    <p>ACME Industries Ltd.<br>Providing reliable tech since 1992</p>
  </div>
  <div>
    <span class="footer-title">Social</span>
    <div class="grid grid-flow-col gap-4">
      <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg></a>
      <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path></svg></a>
      <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path></svg></a>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="navbar bg-base-100 shadow">
  <div class="flex-1">
    <a class="btn btn-ghost normal-case text-xl" href="/">RentalSpace</a>
  </div>
  <div class="flex-none">
    <div class="flex-shrink-0">
      <%= link_to new_space_path, class: 'btn btn-primary btn-sm' do %>
        <svg class="ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd" />
        </svg>
        <span>New Space</span>
      <% end %>
    </div>
    <div class="dropdown dropdown-end">
      <button class="btn btn-ghost btn-circle">
        <div class="indicator">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" /></svg>
          <span class="badge badge-xs badge-primary indicator-item"></span>
        </div>
      </button>
      <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52 ">
        <li><a>お知らせ1</a></li>
        <li><a>お知らせ2</a></li>
        <li><a>お知らせ3</a></li>
      </ul>
    </div>
    <div class="dropdown dropdown-end">
      <label tabindex="0" class="btn btn-ghost btn-circle avatar">
        <div class="w-10 rounded-full">
          <img src="https://api.lorem.space/image/face?hash=33791" />
        </div>
      </label>
      <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
        <li>
          <a class="justify-between">
            Profile
            <span class="badge">New</span>
          </a>
        </li>
        <li><a>Settings</a></li>
        <li><a>Logout</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search_form.html.erb
<%= search_form_for @q, url: spaces_path, class: 'flex justify-center gap-3' do |f| %>
  <%= f.collection_select :space_types_id_eq, SpaceType.all, :id, :name, { include_blank: '会場タイプ' }, class: 'select select-bordered w-full max-w-xs' %>
  <%= f.search_field :name_or_description_or_address_or_nearest_station_cont, class: 'input input-bordered w-full max-w-xs', placeholder: 'キーワード' %>
  <%# モーダルのボタン %>
  <label for="my-modal" class="btn modal-button">こだわり条件</label>

  <input type="checkbox" id="my-modal" class="modal-toggle" />
  <div class="modal">
    <div class="modal-box">
      <h3 class="font-bold text-lg">こだわり条件</h3>
      <%= f.collection_check_boxes :features_id_eq_any, Feature.all, :id, :name do |b| %>
        <%= b.label class: 'label cursor-pointer justify-start gap-3' do %>
        <%= b.check_box class: 'checkbox checkbox-primary' %>
        <span class="label-text"><%= b.text %></span>
        <% end %>
      <% end %>
      <div class="modal-action">
        <label for="my-modal" class="btn">決定</label>
      </div>
    </div>
  </div>
  <%= f.submit class: 'btn btn-primary'%>
<% end %>

app/views/shared/flash/_flash.html.erb
<div class="m-10">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %> shadow-lg">
      <div>
        <%= render "shared/flash/icons/#{message_type}"%>
        <span><%= message %></span>
      </div>
    </div>
  <% end %>
</div>

<div class="alert-success alert-error alert-info alert-warning"></div>

app/views/shared/flash/icons/_error.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>

app/views/shared/flash/icons/_info.html.erb
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current flex-shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>

app/views/shared/flash/icons/_success.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>

app/views/shared/flash/icons/_warning.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>

app/views/spaces/_form.html.erb
<%= form_with model: space, data: { controller: 'set-location' } do |f| %>
  <div class="form-control w-full max-w-xs mb-5">
    <%= f.label :name, class: 'label' %>
    <%= f.text_field :name, class: 'input input-bordered w-full max-w-xs'%>
  </div>

  <div class="form-control w-full max-w-xs mb-5">
    <%= f.label :description, class: 'label' %>
    <%= f.text_area :description, class: 'textarea textarea-bordered w-full max-w-xs' %>
  </div>

  <div class="form-control w-full max-w-xs mb-5">
    <%= f.label :address, class: 'label' %>
    <%= f.text_field :address, class: 'input input-bordered w-full max-w-xs'%>
  </div>

  <div class="form-control w-full max-w-xs mb-5">
    <%= f.label :nearest_station, class: 'label' %>
    <%= f.text_field :nearest_station, class: 'input input-bordered w-full max-w-xs'%>
  </div>
  
  <%# スペースタイプ %>
  <div class="form-control w-full max-w-xs mb-5">
    <%= f.label :space_types, class: 'label' %>
    <div class="flex flex-wrap gap-5">
      <%= f.collection_check_boxes :space_type_ids, SpaceType.all, :id, :name do |b| %>
        <%= b.label class: 'label cursor-pointer justify-start gap-3' do %>
          <%= b.check_box class: 'checkbox checkbox-primary' %>
          <span class="label-text"><%= b.text %></span>
        <% end %>
      <% end %>
    </div>
  </div>

  <%# features %>
  <div class="form-control w-full max-w-xs mb-5">
    <%= f.label :features, class: 'label' %>
    <div class="flex flex-wrap gap-5">
      <%= f.collection_check_boxes :feature_ids, Feature.all, :id, :name do |b| %>
        <%= b.label class: 'label cursor-pointer justify-start gap-3' do %>
          <%= b.check_box class: 'checkbox checkbox-primary' %>
          <span class="label-text"><%= b.text %></span>
        <% end %>
      <% end %>
    </div>  
  </div>

  <%# 緯度経度 %>
  <div class="flex gap-5">
    <div class="form-control w-full max-w-xs mb-5">
      <%= f.label :latitude, class: 'label' %>
      <%= f.text_field :latitude, class: 'input input-bordered w-full max-w-xs bg-gray-100', readonly: true, data: { set_location_target: 'latitude' } %>
    </div>

    <div class="form-control w-full max-w-xs mb-5">
      <%= f.label :longitude, class: 'label' %>
      <%= f.text_field :longitude, class: 'input input-bordered w-full max-w-xs bg-gray-100', readonly: true, data: { set_location_target: 'longitude' } %>
    </div>
  </div>

  <%# 地図を表示してピンを立てる %>
  <p>クリックしてピンを立ててください</p>
  <div data-set-location-target="map" class="h-[500px] mb-5"></div>

  <%# 画像を選択する %>
  <div class="form-control w-full max-w-xs mb-5">
    <%= f.label :images, class: 'label' %>
    <%= f.file_field :images, class: '#', multiple: true %>
  </div>

  <%# 送信ボタン %>
  <div class="mt-3">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/spaces/_space.html.erb
<%= link_to space_path(space), class:'block hover:opacity-80' do %>
  <div class="card lg:card-side bg-base-100 shadow-xl mb-5">
    <figure><%= image_tag space.main_image, size: '400x225' %></figure>
    <div class="card-body">
      <h2 class="card-title"><%= space.name %></h2>
      <div class="flex gap-1 items-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd" />
        </svg>
        <%= space.address %>
      </div>
      <div class="flex gap-1 items-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M4 4a2 2 0 012-2h8a2 2 0 012 2v12a1 1 0 110 2h-3a1 1 0 01-1-1v-2a1 1 0 00-1-1H9a1 1 0 00-1 1v2a1 1 0 01-1 1H4a1 1 0 110-2V4zm3 1h2v2H7V5zm2 4H7v2h2V9zm2-4h2v2h-2V5zm2 4h-2v2h2V9z" clip-rule="evenodd" />
        </svg>
        <%= space.nearest_station %>
      </div>
      <div class="rating">
        <input type="radio" name="rating-<%= space.id %>" class="mask mask-star-2 bg-orange-400" />
        <input type="radio" name="rating-<%= space.id %>" class="mask mask-star-2 bg-orange-400" checked />
        <input type="radio" name="rating-<%= space.id %>" class="mask mask-star-2 bg-orange-400" />
        <input type="radio" name="rating-<%= space.id %>" class="mask mask-star-2 bg-orange-400" />
        <input type="radio" name="rating-<%= space.id %>" class="mask mask-star-2 bg-orange-400" />
      </div>
      <div>
        <% space.features.each do |feature| %>
          <div class="badge badge-outline"><%= feature.name %></div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/spaces/edit.html.erb
<div class="container mx-auto py-10 px-4">
  <%= render 'form', space: @space %>
</div>

app/views/spaces/index.html.erb
<div class="container mx-auto px-4 py-10">
  <div class="mb-3">
    <%= render 'shared/search_form' %>
  </div>
  <div class="flex justify-center mb-5">
    <%== pagy_nav(@pagy) %>
  </div>

  <%= render @spaces %>

  <div  class="flex justify-center">
    <%== pagy_nav(@pagy) %>
  </div>
</div>

app/views/spaces/new.html.erb
<div class="container mx-auto py-10 px-4">
  <%= render 'form', space: @space %>
</div>

app/views/spaces/show.html.erb
<div class="container mx-auto px-4 py-10 prose">
  <div class="text-right">
    <%= link_to edit_space_path(@space), class: 'btn btn-circle ctn-outline' do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z" />
        <path fill-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" clip-rule="evenodd" />
      </svg>
    <% end %>
  </div>
  <h2><%= @space.name%></h2>
    <div class="rating">
      <input type="radio" name="rating-<%= @space.id %>" class="mask mask-star-2 bg-orange-400" />
      <input type="radio" name="rating-<%= @space.id %>" class="mask mask-star-2 bg-orange-400" checked />
      <input type="radio" name="rating-<%= @space.id %>" class="mask mask-star-2 bg-orange-400" />
      <input type="radio" name="rating-<%= @space.id %>" class="mask mask-star-2 bg-orange-400" />
      <input type="radio" name="rating-<%= @space.id %>" class="mask mask-star-2 bg-orange-400" />
    </div>

  <div class="flex flex-wrap gap-3">
    <% @space.space_types.each do |space_type| %>
      <span class="py-1 px-2 border-solid border block"><%= space_type.name %></span>
    <% end %>
  </div>

  <div class="carousel w-full">
    <% @space.images.each do |image| %>
      <div id="<%= dom_id(image) %>" class="carousel-item w-full">
        <%= image_tag image, class: 'w-full' %>
      </div>
    <% end %>
  </div>

  <div class="flex justify-center w-full py-2 gap-2">
    <% @space.images.each.with_index(1) do |image, index| %>
      <a href="#<%= dom_id(image) %>" class="btn btn-xs"><%= index %></a>
    <% end %>
  </div>

  <div>
    <%= simple_format(@space.description)%>
  </div>

  <hr>
  <div class="border-solid border p-5 mb-10">
    <div class="flex gap-1 items-center mb-3">
      住所
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd" />
      </svg>
      <%= @space.address %>
    </div>
    <div class="flex gap-1 items-center mb-3">
      最寄駅
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M4 4a2 2 0 012-2h8a2 2 0 012 2v12a1 1 0 110 2h-3a1 1 0 01-1-1v-2a1 1 0 00-1-1H9a1 1 0 00-1 1v2a1 1 0 01-1 1H4a1 1 0 110-2V4zm3 1h2v2H7V5zm2 4H7v2h2V9zm2-4h2v2h-2V5zm2 4h-2v2h2V9z" clip-rule="evenodd" />
      </svg>
      <%= @space.nearest_station %>
    </div>

    <div>
      <% @space.features.each do |feature| %>
        <div class="badge badge-outline"><%= feature.name %></div>
      <% end %>
    </div>
  </div>
  <div
    data-controller="map"
    data-map-latitude-value="<%= @space.latitude %>"
    data-map-longitude-value="<%= @space.longitude %>"
    class="h-[400px]">
  </div>
</div>